# Sidebar navigation

- label: 'About'
  link: '/about'
- label: 'Collaborators & Contributors'
  link: '/cnc'

- label: 'Tabletop Games'
  items:
    - label: 'Series'
      link: "/series"
      items:
        
    - label: 'MicroTTRPG'
      items:
        - label: 'All Of the Stars in the Sky'
          link: '/TabletopGames/MicroTTRPG/AllTheStarsInTheSky'
        - label: 'i wish i was as strong as i make myself out to be'
          link: '/TabletopGames/MicroTTRPG/i-wish-i-was-as-strong'
        - label: 'Its Dangerous To Go Alone — Take This'
          link: '/TabletopGames/MicroTTRPG/ItsDangerousToGoAlone'
        - label: 'if we dont talk again remember that i love you'
          link: '/TabletopGames/MicroTTRPG/if-we-dont-talk'
        - label: 'Jinkys!'
          link: '/TabletopGames/MicroTTRPG/Jinkys'

- label: 'Visual Novels'
  items:
    - label: 'All The Faces of Dante Hall'
      link: '/VisualNovels/All The Faces of Dante Hall'
    - label: 'Hurricane Like Me'
      link: '/VisualNovels/Hurricane-Like-Me'
    - label: 'Magical Space Adventures'
      link: '/VisualNovels/msa-vn'

- label: 'Events'
  items:
    - label: 'Game Jams'
      items:
        - label: 'Grrls Make Games: A Riot Grrrl Themed Game Jam'
          link: '/hosted-events/jam-events/GrrlsMakeGames'
        
        - label: 'Turn Based Tactics Jam'
          link: '/hosted-events/jam-events/TurnBasedTactics'
        
        - label: 'Release the Magic! A Queer Magical Girl Game Jam'
          link: '/hosted-events/jam-events/ReleasetheMagic'

- label: 'Other'
  items:
    - label: 'FAQ'
      link: '/faq'
    - label: 'Contact Me'
      link: '/contact'
    - label: 'Github'
      link: 'https://github.com/MargaretCatter'
    # - label: 'Info'
    #   link: 'https://info.margaretcatter.dev'
